POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF1dHR1IiwiaWQiOiI2YTI2M2ZmMTVlNGQ3MDk0MWZjNTA1Y2MiLCJpYXQiOjE3ODA4OTI5NjJ9.LqR5CxoRj4fO4Uzm-DTH_VPcm8ExJnxxv4rEFJ7BdZ4

{
    "title" : "never again",
    "author" : "man who drowned",
    "url" : "http://drown.com",
    "likes" : 69
}